name: Test on Windows
on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test_windows:
        strategy:
            matrix:
                os: [windows-2019]

        runs-on: ${{ matrix.os }}

        steps:
        - name: Checkout source
          uses: actions/checkout@v3
            
        - name: Install .NET SDK 6.0
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: "6"

        # setup with colcon fails
        # (probably since it is already installed in the toolscache)
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.8"

        - name: Install dependencies
          shell: pwsh
          run: |  # junction is required since Python path is hardcoded
            New-Item -ItemType Junction -Path "C:\Python38" -Target $Env:Python3_ROOT_DIR
            choco install --no-progress -y vcredist2013 vcredist140 openssl cmake wget

        - name: Install ROS2 dependencies
          run: |
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/asio.1.12.1.nupkg
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/bullet.3.17.nupkg
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/cunit.2.1.3.nupkg
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/eigen.3.3.4.nupkg
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/tinyxml-usestl.2.6.2.nupkg
            wget.exe --quiet https://github.com/ros2/choco-packages/releases/download/2022-03-15/tinyxml2.6.0.0.nupkg
            choco install --no-progress -y --source . asio bullet cunit eigen tinyxml-usestl tinyxml2

        - name: Install Python Packages
          run: |
            python -m pip install -U pip setuptools==59.6.0
            python -m pip install -U catkin_pkg cryptography empy importlib-metadata lark==1.1.1 lxml matplotlib netifaces numpy opencv-python PyQt5 pillow psutil pycairo pydot pyparsing==2.4.7 pyyaml rosdistro rosdep vcstool colcon-common-extensions

        - name: Setup ROS2
          shell: pwsh
          run: |
            wget.exe --quiet https://github.com/ros2/ros2/releases/download/release-humble-20230213/ros2-humble-20230127-windows-release-amd64.zip
            Expand-Archive -Path ros2-humble-20230127-windows-release-amd64.zip -DestinationPath C:\dev

        - name: Invoke Windows build
          shell: pwsh
          run: |  # prevent cmake from searching for higher Python versions in the toolscache
            . C:/dev/ros2-windows/setup.ps1
            ./get_repos.ps1
            colcon build `
            --merge-install `
            --event-handlers console_direct+ `
            --cmake-args `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_TESTING=1 `
            -DPython3_ROOT_DIR=C:/Python38 `
            -DPython3_FIND_STRATEGY=LOCATION `
            -DPython3_FIND_REGISTRY=NEVER `
            --no-warn-unused-cli `
            --packages-up-to ros2cs_tests
          env:
            VisualStudioVersion: "16.0"
      
        - name: Invoke Windows test script
          shell: pwsh
          run: |
            . C:/dev/ros2-windows/setup.ps1
            ./test.ps1
          env:
            VisualStudioVersion: "16.0"
